/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Negocio.Logica;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;


/**
 *
 * @author Sistemas
 */
public class frmCodigoPostal extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmCodigoPostal
     */
    public frmCodigoPostal() {
        initComponents();
        setFrameIcon(new ImageIcon("/Images/greed.png"));
        this.getContentPane().setBackground(Color.WHITE);
        
        //Image icon=Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/greed.png"));
        //setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEntidad = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblEntidad = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblMunicipio = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMunicipio = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lblCodigoP = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCP = new javax.swing.JTable();
        btnAgregarCP = new javax.swing.JButton();
        btnListaCP = new javax.swing.JButton();
        btnListaMuni = new javax.swing.JButton();
        btnEditarCP = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setClosable(true);
        setTitle("Entidades federativas, municipios y códigos postales");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/greedICO.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jScrollPane1.setBorder(null);

        tblEntidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblEntidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEntidadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEntidad);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setText("Entidad Federativa");

        lblEntidad.setBackground(new java.awt.Color(255, 255, 255));
        lblEntidad.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblEntidad.setForeground(new java.awt.Color(3, 36, 72));
        lblEntidad.setText("estado");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setText("Municipio");

        lblMunicipio.setBackground(new java.awt.Color(255, 255, 255));
        lblMunicipio.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblMunicipio.setForeground(new java.awt.Color(3, 36, 72));
        lblMunicipio.setText("municipio");

        tblMunicipio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblMunicipio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMunicipioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMunicipio);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setText("Código Postal");

        lblCodigoP.setBackground(new java.awt.Color(255, 255, 255));
        lblCodigoP.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblCodigoP.setForeground(new java.awt.Color(3, 36, 72));
        lblCodigoP.setText("codigo");

        tblCP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblCP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCPMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblCP);

        btnAgregarCP.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarCP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Create.png"))); // NOI18N
        btnAgregarCP.setToolTipText("Nuevo");
        btnAgregarCP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAgregarCP.setBorderPainted(false);
        btnAgregarCP.setContentAreaFilled(false);
        btnAgregarCP.setEnabled(false);
        btnAgregarCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCPActionPerformed(evt);
            }
        });

        btnListaCP.setBackground(new java.awt.Color(255, 255, 255));
        btnListaCP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/List.png"))); // NOI18N
        btnListaCP.setToolTipText("Mostrar Códigos Postales");
        btnListaCP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnListaCP.setBorderPainted(false);
        btnListaCP.setContentAreaFilled(false);
        btnListaCP.setEnabled(false);
        btnListaCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaCPActionPerformed(evt);
            }
        });

        btnListaMuni.setBackground(new java.awt.Color(255, 255, 255));
        btnListaMuni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/List.png"))); // NOI18N
        btnListaMuni.setToolTipText("Mostrar municipios");
        btnListaMuni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnListaMuni.setBorderPainted(false);
        btnListaMuni.setContentAreaFilled(false);
        btnListaMuni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaMuniActionPerformed(evt);
            }
        });

        btnEditarCP.setBackground(new java.awt.Color(255, 255, 255));
        btnEditarCP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Modify.png"))); // NOI18N
        btnEditarCP.setToolTipText("Editar");
        btnEditarCP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEditarCP.setBorderPainted(false);
        btnEditarCP.setContentAreaFilled(false);
        btnEditarCP.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblEntidad))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(lblCodigoP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarCP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarCP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListaCP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lblMunicipio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListaMuni, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(lblEntidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMunicipio))
                    .addComponent(btnListaMuni, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblCodigoP))
                                .addComponent(btnListaCP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnEditarCP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAgregarCP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        lblEntidad.setText("");
        lblMunicipio.setText("");
        lblCodigoP.setText("");
        llenarEntidades();
    }//GEN-LAST:event_formInternalFrameActivated

    private void tblEntidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEntidadMouseClicked
        // TODO add your handling code here:
        int row=tblEntidad.rowAtPoint(evt.getPoint());
        lblEntidad.setText((String)tblEntidad.getModel().getValueAt(row, 1));
        tblMunicipio.setModel(new DefaultTableModel());
        tblCP.setModel(new DefaultTableModel());
        lblMunicipio.setText("");
        lblCodigoP.setText("");
        btnListaCP.setEnabled(false);
        btnAgregarCP.setEnabled(false);
        btnEditarCP.setEnabled(false);
    }//GEN-LAST:event_tblEntidadMouseClicked

    private void btnListaMuniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaMuniActionPerformed
        // TODO add your handling code here:
       llenarMunicipios();
    }//GEN-LAST:event_btnListaMuniActionPerformed

    private void tblMunicipioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMunicipioMouseClicked
        // TODO add your handling code here:
        int row=tblMunicipio.rowAtPoint(evt.getPoint());
        lblMunicipio.setText((String)tblMunicipio.getModel().getValueAt(row, 1));
        tblCP.setModel(new DefaultTableModel());
        lblCodigoP.setText("");
        btnListaCP.setEnabled(true);
        btnAgregarCP.setEnabled(false);
        btnEditarCP.setEnabled(false);
    }//GEN-LAST:event_tblMunicipioMouseClicked

    private void btnListaCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaCPActionPerformed
        // TODO add your handling code here:
        llenarCP();
        btnEditarCP.setEnabled(true);
        btnAgregarCP.setEnabled(true);
    }//GEN-LAST:event_btnListaCPActionPerformed

    private void tblCPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCPMouseClicked
        // TODO add your handling code here:
        int row=tblCP.rowAtPoint(evt.getPoint());
        lblCodigoP.setText((String)tblCP.getModel().getValueAt(row, 1));
    }//GEN-LAST:event_tblCPMouseClicked

    private void btnAgregarCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCPActionPerformed
        // TODO add your handling code here:
        Frame f=JOptionPane.getFrameForComponent(this);
        frmDetalleCodigoP cp=new frmDetalleCodigoP("Nuevo",f, true,(int)tblEntidad.getModel().getValueAt(tblEntidad.getSelectedRow(), 0),(int)tblMunicipio.getModel().getValueAt(tblMunicipio.getSelectedRow(), 0),0);
        cp.addWindowListener(new WindowAdapter() {
           @Override
                public void windowClosed(WindowEvent e){
                    llenarCP();
                }
        });
        Dimension desktopSize = this.getParent().getSize();
        Dimension FrameSize = cp.getSize();
        cp.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        cp.setVisible(true);
        
    }//GEN-LAST:event_btnAgregarCPActionPerformed
    public void llenarCP(){
        try{
            Logica oLogica=new Logica();
            ResultSet cp=oLogica.CP((int) tblMunicipio.getModel().getValueAt(tblMunicipio.getSelectedRow(),0));
            String[] titulos={"Código","Colonia","Código Postal"};
            DefaultTableModel codigop=new DefaultTableModel(null, titulos){
                public boolean isCellEditable(int rowIndex, int mColIndex) {
                return false;
                }};
            Object[] fila=new Object[3];
            if(cp!=null){
                while(cp.next()){
                    fila[0]=cp.getInt(1);
                    fila[1]=cp.getString(2);
                    fila[2]=cp.getString(3);
                    codigop.addRow(fila);
                }
                tblCP.setModel(codigop);
                tblCP.setAutoCreateColumnsFromModel(true);
                JTableColumnsWidth.setWidth(tblCP,611,10,70,20);
                tblCP.setRowSelectionInterval(0, 0);
                lblCodigoP.setText((String) tblCP.getModel().getValueAt(0, 1));
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    public void llenarEntidades(){
        try{
            Logica oLogica=new Logica();
            ResultSet ent=oLogica.Entidades();
            String[] titulos={"Código","Entidad federativa","Abreviatura"};
            DefaultTableModel entidades=new DefaultTableModel(null, titulos){
                public boolean isCellEditable(int rowIndex, int mColIndex) {
                return false;
                }};
            int[] ancho={5,100,8};
            Object[] fila=new Object[3];
            if (ent!=null){
                while(ent.next()){
                    fila[0]=ent.getInt(1);
                    fila[1]=ent.getString(2);
                    fila[2]=ent.getString(3);
                    entidades.addRow(fila);
                }
                tblEntidad.setModel(entidades);
                tblEntidad.setAutoCreateColumnsFromModel(true);
                JTableColumnsWidth.setWidth(tblEntidad,611,10,70,20 );
                tblEntidad.setRowSelectionInterval(0, 0);
                lblEntidad.setText((String)tblEntidad.getModel().getValueAt(0, 1));
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    void llenarMunicipios(){
         try{
            Logica oLogica=new Logica();
            ResultSet muni=oLogica.Municipios((int) tblEntidad.getModel().getValueAt(tblEntidad.getSelectedRow(),0));
            String[] titulos={"Código","Municipio"};
            DefaultTableModel municipios=new DefaultTableModel(null, titulos){
                public boolean isCellEditable(int rowIndex, int mColIndex) {
                return false;
                }};
            int[] ancho={10,60};
            Object[] fila=new Object[2];
            if(muni!=null){
                while(muni.next()){
                    fila[0]=muni.getInt(1);
                    fila[1]=muni.getString(2);
                    municipios.addRow(fila);
                }
                tblMunicipio.setModel(municipios);
                tblMunicipio.setAutoCreateColumnsFromModel(true);
                JTableColumnsWidth.setWidth(tblMunicipio, 611, 10,60);
                tblMunicipio.setRowSelectionInterval(0, 0);
                lblMunicipio.setText((String)tblMunicipio.getModel().getValueAt(0, 1));
                btnListaCP.setEnabled(true);
            }
            
        }catch (Exception e){
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCP;
    private javax.swing.JButton btnEditarCP;
    private javax.swing.JButton btnListaCP;
    private javax.swing.JButton btnListaMuni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCodigoP;
    private javax.swing.JLabel lblEntidad;
    private javax.swing.JLabel lblMunicipio;
    private javax.swing.JTable tblCP;
    private javax.swing.JTable tblEntidad;
    private javax.swing.JTable tblMunicipio;
    // End of variables declaration//GEN-END:variables
}
