/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;
import Negocio.Logica;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileOutputStream;
import java.io.FileInputStream;
import java.io.InputStream;
import java.io.IOException;
import java.util.Properties;
import javax.swing.JOptionPane;
/**
 *
 * @author SISTEMAS6
 */

public class frmConfiguracion extends javax.swing.JFrame {

    /**
     * Creates new form frmConfiguracion
     */
    public frmConfiguracion() {
        initComponents();
         Image icon=Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/cacao.png"));
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblPuerto = new javax.swing.JLabel();
        lblBasededatos = new javax.swing.JLabel();
        lblIpserver = new javax.swing.JLabel();
        txtIpserver = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtPuerto = new javax.swing.JTextField();
        txtBasededatos = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        lblTituloFormurario = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnTest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configurador Sistemas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblUsuario.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblUsuario.setText("Usuario:");

        lblContraseña.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblContraseña.setText("Contraseña:");

        lblPuerto.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblPuerto.setText("Puerto:");

        lblBasededatos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblBasededatos.setText("Base De Datos:");

        lblIpserver.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblIpserver.setText("IP Server:");

        txtIpserver.setName("txtIpserver"); // NOI18N

        lblTituloFormurario.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        btnGuardar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnTest.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnTest.setText("Test De Conexion");
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblIpserver)
                                            .addGap(56, 56, 56)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblContraseña)
                                            .addComponent(lblBasededatos)
                                            .addComponent(lblPuerto))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIpserver)
                                    .addComponent(txtUsuario)
                                    .addComponent(txtContraseña)
                                    .addComponent(txtPuerto)
                                    .addComponent(txtBasededatos, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(btnTest)))
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lblTituloFormurario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(128, 128, 128))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloFormurario, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIpserver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIpserver))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContraseña))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPuerto))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBasededatos)
                    .addComponent(txtBasededatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTest, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    
        String IP = txtIpserver.getText();
        String User = txtUsuario.getText();
        String Pass = new String(txtContraseña.getPassword());
        String Port = txtPuerto.getText();
        String Db = txtBasededatos.getText();
        
        Properties prop = new Properties();

        prop.setProperty("IPSERVER", IP);
        prop.setProperty("USUARIO", User);
        prop.setProperty("PASSWORD", Pass);
        prop.setProperty("PUERTO", Port);
        prop.setProperty("DB", Db);
        prop.setProperty("CHECK", "1");
        
        FileOutputStream Os = null;

        {

            try 
            
            {
                Os = new FileOutputStream("config.cao");
                prop.store(Os,"Archivo De Configuracion");
                JOptionPane.showMessageDialog(null, "Datos Guardados Correctamente");
                this.dispose();
                //frmLogin.Reset();
            }
        
            catch(IOException ioe)
                
            {
                System.out.println("Error Al Guardar Datos" + ioe.getMessage());       
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
          lblTituloFormurario.setText("Archivo De Configuracion");
//
//        Properties Proplect = new Properties();
//        InputStream Entra = null;
//      
//        try
//        
//        {
//            Entra = new FileInputStream("Configuration.Matrix");
//            Proplect.load(Entra);
//            
//            txtIpserver.setText(Proplect.getProperty("IPSERVER"));
//            txtUsuario.setText(Proplect.getProperty("USUARIO"));
//            txtContraseña.setText(Proplect.getProperty("PASSWORD"));
//            txtPuerto.setText(Proplect.getProperty("PUERTO"));
//            txtBasededatos.setText(Proplect.getProperty("DB"));
//
//            JOptionPane.showMessageDialog(null, "Datos Cargados Correctamente");
//        }
//        
//        catch(IOException ex)
//            
//        {
//            ex.printStackTrace();
//        }
//        
//        finally
//        
//        {
//           if (Entra != null)
//           
//           {
//               try
//               
//               {
//                   Entra.close();
//               }
//               
//               catch (IOException e)
//               
//               {
//                   e.printStackTrace();
//               }
//           }
//        }
    }//GEN-LAST:event_formWindowOpened

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
        // TODO add your handling code here:
       Logica Ln = new Negocio.Logica();
       
       try
       
       {
           if(Ln.TestCon(txtIpserver.getText(), new String(txtContraseña.getPassword()), txtPuerto.getText(), txtBasededatos.getText(), txtUsuario.getText())){
           JOptionPane.showMessageDialog(null,"Conexion Correcta","Confirmacion",JOptionPane.INFORMATION_MESSAGE);
           btnGuardar.setEnabled(true);
           }
           else{
           JOptionPane.showMessageDialog(null,"Error Al Conectar A La Base De Datos" ,"Advertencia",JOptionPane.WARNING_MESSAGE);
           btnGuardar.setEnabled(false);
           }
       }
       
       catch(Exception ex)
           
       {
           JOptionPane.showMessageDialog(null, ex);
       } 
    }//GEN-LAST:event_btnTestActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        //frmLogin.Reset();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnTest;
    private javax.swing.JLabel lblBasededatos;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblIpserver;
    private javax.swing.JLabel lblPuerto;
    private javax.swing.JLabel lblTituloFormurario;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtBasededatos;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtIpserver;
    private javax.swing.JTextField txtPuerto;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
