/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Entidades.Empresa;

/**
 *
 * @author Sistemas
 */
public class frmMenusys extends javax.swing.JFrame {

    /**
     * Creates new form fmrMenusys
     */
    public frmMenusys() {
        initComponents();
         setLocationRelativeTo(null);
        Image icon=Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/greed.png"));
        setIconImage(icon);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setTitle("GREED - Sistema de Cartera "+Empresa.getSnombreEmpresa());
        this.setLayout(new BorderLayout());
        this.add(pnlSistema, BorderLayout.CENTER);
        this.pack();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSistema = new javax.swing.JPanel();
        mnbSistema = new javax.swing.JMenuBar();
        mnuCatalogos = new javax.swing.JMenu();
        mnuOperacion = new javax.swing.JMenu();
        mnuAcreditados = new javax.swing.JMenu();
        mniIndividuales = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(6, 66, 125));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setName(""); // NOI18N
        setSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(null);

        pnlSistema.setBackground(new java.awt.Color(255, 255, 255));
        pnlSistema.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        pnlSistema.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlSistema);
        pnlSistema.setBounds(0, 0, 400, 320);

        mnbSistema.setBackground(new java.awt.Color(255, 255, 255));
        mnbSistema.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(3, 36, 72)));
        mnbSistema.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnbSistema.setPreferredSize(new java.awt.Dimension(124, 25));

        mnuCatalogos.setText("Catálogos");
        mnbSistema.add(mnuCatalogos);

        mnuOperacion.setText("Operación");

        mnuAcreditados.setText("Acreditados");

        mniIndividuales.setText("Individuales");
        mniIndividuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniIndividualesActionPerformed(evt);
            }
        });
        mnuAcreditados.add(mniIndividuales);

        mnuOperacion.add(mnuAcreditados);

        mnbSistema.add(mnuOperacion);

        setJMenuBar(mnbSistema);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniIndividualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniIndividualesActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Click");
    }//GEN-LAST:event_mniIndividualesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenusys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenusys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenusys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenusys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenusys().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mnbSistema;
    private javax.swing.JMenuItem mniIndividuales;
    private javax.swing.JMenu mnuAcreditados;
    private javax.swing.JMenu mnuCatalogos;
    private javax.swing.JMenu mnuOperacion;
    private javax.swing.JPanel pnlSistema;
    // End of variables declaration//GEN-END:variables
}
